Add item requests
Den4ik-BMSTU/java-shareit pull request #3
Opened 2023-01-14 15:50 UTC by Den4ik-BMSTU

2023-01-14 19:06 UTC, EvgenyKoptubenko commented
Если есть желание, попробуй добавить параметризованные тесты. https://www.baeldung.com/parameterized-tests-junit-5
Они позволяют сократить количество кода тестов

2023-01-14 19:09 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      public void deleteUser(@PathVariable long userId) {
Если попробовать удалить несуществующего пользователя, то приходит 500
{
	"error": "No class ru.practicum.shareit.user.model.User entity with id 2222 exists!",
	"description": "Unknown"
}

На самом деле это больше похоже на 404

2023-01-14 19:10 UTC, EvgenyKoptubenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      public UserDto createUser(@RequestBody @Valid UserDto userDto) {
Если попробовать добавить второй раз пользователя, то приходит ошибка
{
	"error": "could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
	"description": "Unknown"
}
Попробуй обработать ее, чтобы пользователю показывалась читаемая ошибка

2023-01-14 19:12 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Есть только несколько предложений по улучшению

2023-01-15 21:46 UTC, Den4ik-BMSTU commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      public UserDto createUser(@RequestBody @Valid UserDto userDto) {
Сделал

2023-01-15 21:47 UTC, Den4ik-BMSTU commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      public void deleteUser(@PathVariable long userId) {
Поправил

2023-01-16 18:06 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо

2023-01-16 20:58 UTC, merged